# Content Chunking Configuration with Context Inheritance

chunking:
  # Global settings
  default_strategy: "structure_aware"
  enable_context_inheritance: true
  
  # Document type specific settings
  strategies:
    pdf:
      method: "structure_aware"
      max_tokens: 2000
      min_tokens: 200
      context_inheritance: true
      group_by: "sections"
      max_group_size: 8
      min_group_size: 2
      overlap_ratio: 0.15
      preserve_structure: true
      respect_visual_boundaries: true
      
    docx:
      method: "structure_aware" 
      max_tokens: 1500
      min_tokens: 150
      context_inheritance: true
      group_by: "headings"
      max_group_size: 6
      min_group_size: 2
      overlap_ratio: 0.2
      respect_tables: true
      preserve_formatting: true
      
    xlsx:
      method: "sheet_aware"
      max_tokens: 1000
      min_tokens: 100
      context_inheritance: true
      group_by: "sheets"
      max_group_size: 4
      min_group_size: 2
      overlap_ratio: 0.1
      preserve_data_structure: true
      include_chart_context: true
      
    pptx:
      method: "slide_aware"
      max_tokens: 800
      min_tokens: 80
      context_inheritance: true
      group_by: "topics"
      max_group_size: 5
      min_group_size: 2
      overlap_ratio: 0.1
      preserve_slide_context: true
      include_speaker_notes: true

  # Context inheritance settings
  context_inheritance:
    enabled: true
    max_context_tokens: 300
    min_context_tokens: 50
    context_decay_rate: 0.1
    refresh_after_chunks: 6
    context_quality_threshold: 0.7
    
    # LLM settings for context generation
    llm:
      model: "hochschul-llm"
      temperature: 0.1
      max_tokens: 400
      timeout_seconds: 30
      
    # Context prompt templates
    templates:
      context_generation: "context_generation.txt"
      task_with_context: "task_with_context.txt"
      
  # Visual element integration
  visual_integration:
    include_vlm_descriptions: true
    include_extracted_data: true
    max_visuals_per_chunk: 3
    visual_context_weight: 0.3
    separate_visual_chunks: false
    
  # Token management
  token_management:
    estimation_model: "gpt-3.5-turbo"
    buffer_ratio: 0.1  # 10% safety buffer
    hard_limit_multiplier: 1.2  # 20% above max_tokens before rejection
    
  # Performance settings
  performance:
    enable_async_processing: true
    max_concurrent_groups: 5
    enable_context_caching: true
    cache_ttl_minutes: 60
    
  # Quality control
  quality:
    min_chunk_content_ratio: 0.5  # Minimum content vs total tokens
    max_empty_chunks: 2  # Max empty chunks before error
    validate_context_relevance: true
    context_similarity_threshold: 0.6

# Group formation settings
group_formation:
  # PDF-specific settings
  pdf:
    section_detection:
      heading_patterns:
        - r'^\d+\.?\s+[A-Z]'  # "1. Introduction"
        - r'^[A-Z][A-Z\s]{3,50}$'  # "INTRODUCTION"
        - r'^\d+\.\d+\.?\s+[A-Z]'  # "1.1 Overview"
      structure_markers:
        - "heading"
        - "title" 
        - "caption"
      use_smoldocling_structure: true
      min_section_length: 3  # Minimum segments per section
      
  # DOCX-specific settings  
  docx:
    heading_detection:
      style_patterns:
        - "Heading 1"
        - "Heading 2" 
        - "Heading 3"
        - "Title"
      heading_levels: 3
      respect_outline: true
      min_section_length: 2
      
  # XLSX-specific settings
  xlsx:
    sheet_grouping:
      group_related_sheets: true
      max_sheets_per_group: 3
      respect_sheet_dependencies: true
      include_chart_sheets: true
      
  # PPTX-specific settings
  pptx:
    slide_grouping:
      topic_coherence_threshold: 0.7
      respect_section_slides: true
      max_slides_per_group: 8
      include_hidden_slides: false

# Prompt templates configuration
templates:
  base_path: "plugins/templates"
  
  context_generation:
    default_language: "de"
    supported_languages: ["de", "en"]
    
  prompts:
    context_summary:
      max_length: 300
      focus_areas:
        - "main_concepts"
        - "key_definitions" 
        - "important_references"
        - "visual_elements"
        - "thematic_continuity"
        
    task_integration:
      include_previous_context: true
      context_separator: "\n---\n"
      visual_marker: "[VISUAL]"
      data_marker: "[DATA]"